"""add user

Revision ID: 2869daa0af99
Revises: b422e0f3e0c9
Create Date: 2021-02-28 10:04:57.590933

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2869daa0af99'
down_revision = 'b422e0f3e0c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=128), nullable=False))
    op.drop_column('user', 'is_superuser')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_superuser', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
